name: test
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Pick golang_info
        id: go
        run: echo ::set-output name=version::$(grep golang .tool-versions | awk '{print $2}')

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.go.outputs.version }}

      - run: go test -v -count=1 -race -cover -coverprofile=coverage ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage
          flags: unittests
          name: codecov
          fail_ci_if_error: true
